### ISSUE TITLE
Submission checklist

### ISSUE THREAD

**Issue by tmlai** [tmlai/CMPUT410-TTHE-Group-Project#8]
Purchase module
- [x] view list of product categories
- [x] list of products and can be navigated
- [x] search capability (basic and advanced: based on code,name,cat, price, availability or EVEN weight)
- [x] recommendation capability (query relaxation | rating | associate rule)
- [x] order one product/multiple products
- [x] view shopping cart, modify it, delete it
- [x] view outstanding orders
- [x] REST api ( get list of available products/info of a product/order a product/get delivery date)
- 

Management module
- The following list
- [x] Customer with their aggregated purchase counts and amounts
- [x] List of sold product given a time period with aggregrated purchases and amounts
- [x] external stores - total purchases counts and amounts
- [x] OTHER DECISION SUPPORT REPORTS: e.g. top selling for a given time period

Technical requirement
- [x] data store in Oracle or mysql
- [x] data in E-R model

Submission requirements
- [x] list of database content JUST before the demo
- [x] codebase before the demo 1hr
- [x] documentation in hard copy Wed 10th at 1pm 
- [x] with COVER
- [x] explain how solution is implement, explain assumptions and simplifications
- [x] User queries and how to produce the report for the management module
- [x] Algorithm for recommender system
- [x] snapshot of purchasing module/ management report
- [x] ER diagram
- [x] Enumerate specific features added (?JavaScript enhancement,…?)
- [ ] a tar file includes : report/all source code, no compiled class file

Data requirements
- [x] Product must have (code, cat, name, desc, image, price, weight, dimensions, availability)

**Comment by tmlai** [comment]
Good job guys, we're done!
